version: '3.8'

services:
  jenkins:
    build:
      context: ./jenkins  # Update this path to where your Dockerfile is located
      dockerfile: Dockerfile
    ports:
      - "8080:8080"      # Maps port 8080 on the host to port 8080 on the container
      - "50000:50000"    # Maps port 50000 for Jenkins agents
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375  # Set DOCKER_HOST to connect to Docker Desktop on Windows
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yml
    volumes:
      - jenkins_home:/var/jenkins_home  # Persists Jenkins data

volumes:
  jenkins_home:  # Named volume to persist Jenkins data
